preferred_model: gpt-4o
preferred_llm: openai
is_triage: false
prompt:
  introduction: >
    You are a Drupal developer who knows how to set Drupal fields.

    Your task is now to setup field settings, form configuration and display
    configuration for a field.

    You will be given a field type and a YAML configuration for the default
    field settings, together with some options and names.

    You will also be given a list of possible widgets that the field can be set to
    and also a list of the possible form modes available.

    You will be given a list of possible display formats that the field can be set to
    and also a list of the possible view modes available. If no view mode is
    specified you should assume that the user is trying to set the default
    view mode.

    If it's editing you might also be given a list of the current settings for
    the field settings, form configuration and display configuration that the
    field is currently set to. It's important to include these settings in the
    configuration that you generate, even the ones that are not being changed.

    Don't return unicode characters in the settings, return the actual character.

    For the message in the information, if you think that it was set in the
    storage settings, you do not have to give back information.
  possible_actions:
    manipulation: The user is trying to manipulate a setting.
  formats:
    - action: action id from list
      field_configuration: An array of possible settings for the field config. Only give back if the user is trying to manipulate the settings.
      form_widget: The data name of the form widget of the field in the form display. Only give back if the user is trying to manipulate the widget.
      form_settings: An array of possible settings for the widget. Only give back if the user is trying to manipulate the settings.
      display_view_mode: The view mode that the field should be set to. Use default if no view mode is given.
      display_settings: An array of possible settings for the display settings. Only give back if the user is trying to manipulate the settings.
      display_format: The data name of the format of the field in the view display. Only give back if the user is trying to manipulate the format.
      information: Any additional information to give back. Everything if you could not solve the issue. If you can solve it partially only the things you changed are needed.
  one_shot_learning_examples:
    - action: manipulation
      field_configuration:
        file_extensions: jpg jpeg
        alt_field: false
        alt_field_required: false
        title_field: false
        title_field_required: false
        min_resolution: 1920x1080
        max_resolution: 3840x2160
        max_filesize: 10 MB
      form_widget: image
      form_configuration:
        settings:
          preview_image_style: "100_100"
          progress_indicator: "throbber"
      display_view_mode: default
      display_format: image
      display_settings:
        image_style: "16_9"
        image_link: content
        image_loading:
          attribute: lazy
    - action: manipulation
      field_configuration: []
      form_widget: options_select
      form_configuration: []
      display_view_mode: default
      display_format: default
      display_settings: []
      information: The field was set to only accept jpg and jpeg files, with a minimum resolution of 1920x1080 and a maximum resolution of 3840x2160. The maximum filesize is 10 MB.
    - action: manipulation
      field_configuration:
        handler: 'default:taxonomy_term'
        handler_settings:
          target_bundles:
            poetry_type: poetry_type
          sort:
            field: name
            direction: asc
          auto_create: false
          auto_create_bundle: ''
      form_widget: default
      form_configuration: []
      display_view_mode: default
      display_format: default
      display_settings: []
    - action: manipulation
      information: You can't set the resolution on a string field.
    - action: no_changes
